### ISSUE TITLE
M2 MacBook Air SKU

### ISSUE THREAD

**Issue by 992-911** [worthbak/inventory-checker-app#42]
Hi, I think the SKU for the M2 Air 16GB/1TB in **Silver** is missing.  Great project, BTW.

<img width="405" alt="Screen Shot 2022-07-17 at 10 25 53 AM" src="https://user-images.githubusercontent.com/109479273/179418079-1b29d3f5-1673-4717-84fc-3d45a1c3188b.png">
.

**Comment by worthbak** [comment]
Nice catch, but, interestingly, it actually looks like Apple isn't stocking a Silver version of this SKU in stores (hence its omission from the app). I have basically zero visibility into Apple's inventory management or stocking decisions, but from what I can tell, all product configs they stock in their stores are assigned a `partNumber` like `MK0U3`, `MKGR3`, or `MLXY3` (that's a Studio Display, MacBook Pro, and MacBook Air, respectively). The `partNumber` values for this "ultimate" Air config are:

```
MN703 // Midnight
MNQP3 // Space Gray
MN6Y3 // Starlight
```

If you build the same config on their site, but in Silver, and then sniff the network traffic, you'll just see a `partNumber` of `Z15X`, which AFAICT indicates a CTO build, and _not_ one they plan to stock in-stores. 

Not sure why they left out the Silver model, but that appears to be what they've done - if anybody has any more info (or, to be honest, a more reliable way of discerning this kind of data without hunting and pecking through their online store), I'm all ears. For now, though, this is intentional, and not an accidental omission. 

Also, thanks! Hope the app is working for you.

**Comment by 992-911** [comment]
Great app. Thank you.
