### ISSUE TITLE
Request item - Apple Watch Ultra

### ISSUE THREAD

**Issue by lclamon** [worthbak/inventory-checker-app#62]
Thank you for everything you do, would you consider adding support for the Apple Watch lineup? Thanks!

**Comment by worthbak** [comment]
Yup! Adding Series 8 and Ultra support would make sense - I probably won't have that ready for this week's launch of those products, but hopefully I'll be able to add it sometime soon.

**Comment by ProH8R** [comment]
Placing my vote for this feature too! Would love this to support the Apple Watch Ultra since shipping times are now into the months

**Comment by bfolberth** [comment]
+1 vote :-)

**Comment by Woolax35** [comment]
another vote here,  looking for the ultra

**Comment by jackonawalk** [comment]
+1

**Comment by firenze22** [comment]
yes, this please!

**Comment by worthbak** [comment]
Good to know that quite a few people want support for this product! I'm working on adding it to InventoryWatch, but Apple has made it a bit gnarly to find the correct SKUs for each model (there are different variations for each band color and size, and the actual SKUs vary between countries, _and_ all of the correct data is spread across different pages on Apple's store). So, I'm working on it, but it's not as easy as adding some other products. 

(If anybody has any bright ideas on an easy way to compile this data for individual countries, I'm all ears!)

**Comment by 41DMBfan** [comment]
> Good to know that quite a few people want support for this product! I'm working on adding it to InventoryWatch, but Apple has made it a bit gnarly to find the correct SKUs for each model (there are different variations for each band color and size, and the actual SKUs vary between countries, _and_ all of the correct data is spread across different pages on Apple's store). So, I'm working on it, but it's not as easy as adding some other products.
> 
> (If anybody has any bright ideas on an easy way to compile this data for individual countries, I'm all ears!)

How do you locate the SKU online? I'm happy to help gather that info.

**Comment by dareiff** [comment]
Are these SKUs universal? Best Buy has them right on the category results page: [https://www.bestbuy.com/site/apple-watch-device-accessories/apple-watch-ultra/pcmcat1662589086930.c?id=pcmcat1662589086930](best buy)

**Comment by 41DMBfan** [comment]
When I try to search for a custom sku in preferences using any of the sku numbers from Best Buy, I see no change or search of any kind. Am I doing something wrong? Are the skus from Best Buy incorrect?

**Comment by dareiff** [comment]
> When I try to search for a custom sku in preferences using any of the sku numbers from Best Buy, I see no change or search of any kind. Am I doing something wrong? Are the skus from Best Buy incorrect?

Use this: **MQET3LL/A**

<img width="1084" alt="Screenshot 2022-09-27 at 12 57 23 PM" src="https://user-images.githubusercontent.com/435896/192623448-21c9e384-29a3-41eb-9e8f-79c445cad347.png">
<img width="1012" alt="Screenshot 2022-09-27 at 12 57 21 PM" src="https://user-images.githubusercontent.com/435896/192623461-ae4bfb64-9c0e-4b00-b6ac-c644784850a3.png">

**Comment by worthbak** [comment]
> When I try to search for a custom sku in preferences using any of the sku numbers from Best Buy, I see no change or search of any kind. Am I doing something wrong? Are the skus from Best Buy incorrect?

yeah, Apple's SKUs don't map to the ones visible in Best Buy's website, because Apple Stores stock based on the watch+band+band-size config, while Best Buy only shows the watch+band model root. kinda confusing, but if @dareiff seems to be on the right track in finding a model number that is actually stocked by Apple Stores.

something I really need to do is write up a how-to on finding these model numbers from Apple's website, but it's tough because the method for finding model number varies based on the product. in any case, if anybody wants to track availability while I'm working on this update, try this: 
* go to [the Apple Watch Ultra buyer page](https://www.apple.com/shop/buy-watch/apple-watch-ultra) and select a watch model
* on the next page, select your band size (small/medium/large)
* then, click the `Check availability` button (under Pickup, near Add to Bag)
* when the Select a location modal appears, open your browser's developer tools (`menu+command+i` in Chrome) and select the Network tab
* enter your location as directed by the modal (city or ZIP in the US) and click search
* you should see an entry like this appear in the network request list: `fulfillment-messages?searchNearby=true&parts.0=MQEU3LL/A&option.0=MQFY3LL/A,MQE03AM/A&location=09875`
* from that request URL, find the `parts.0` parameter (in the above example, it was `MQEU3LL/A`)
* copy that value, and add it to InventoryWatch's Custom SKU setting (as described by @dareiff above)

that will trigger alerts when that specific model is found, which obviously isn't ideal if you're ok with finding a variety of models, but is a decent temporary workaround 👍

**Comment by worthbak** [comment]
InventoryWatch has been updated to support the Apple Watch Ultra 🎉 download the new version `v0.1.5` here: https://worthbak.github.io/inventory-checker-app/
